<script setup lang="ts">
import { Heart } from '@lucide/vue'
const quotes=['今天也别忘了好好吃饭。','下班路上慢一点，我等你。','想起你时，心里会安静一下。','有你在，回家这件事就有了方向。','今天的快乐，想第一个告诉你。','我们不赶时间，慢慢把日子过好。','你忙你的，我会一直在。','下次见面，记得多抱一会儿。','一起买菜、散步、看电影，已经很幸福。','谢谢你愿意听我说这些小事。','天气好的时候，想和你去晒晒太阳。','不需要每天都特别，陪着就很好。']
const index=ref(Math.floor(Date.now()/86400000)%quotes.length);let timer:ReturnType<typeof setInterval>|undefined
onMounted(()=>timer=setInterval(()=>index.value=(index.value+1)%quotes.length,10000));onBeforeUnmount(()=>{if(timer)clearInterval(timer)})
</script>
<template><section class="quote-stage"><div class="quote-mark"><Heart :size="22" fill="currentColor"/></div><div class="quote-copy"><span>今日情话</span><Transition name="quote" mode="out-in"><p :key="index">{{quotes[index]}}</p></Transition></div></section></template>
<style scoped>
.quote-stage{position:relative;display:grid;grid-template-columns:auto 1fr;align-items:center;gap:20px;min-height:136px;margin-top:20px;padding:27px clamp(22px,4vw,46px);overflow:hidden;border:1px solid rgba(255,255,255,.9);border-radius:26px;background:linear-gradient(120deg,rgba(255,252,255,.92),rgba(245,219,249,.86),rgba(222,235,252,.78));box-shadow:0 18px 46px rgba(106,55,125,.12),inset 0 1px rgba(255,255,255,.9)}.quote-stage::after{content:'“';position:absolute;right:6%;top:-48px;color:rgba(161,76,156,.09);font-family:serif;font-size:190px}.quote-mark{position:relative;z-index:1;display:grid;place-items:center;width:52px;height:52px;border-radius:18px;background:linear-gradient(135deg,#edd4fa,#f9c9df,#bfe0f6);color:#bf5d91;box-shadow:0 10px 22px rgba(171,82,145,.17)}.quote-copy{position:relative;z-index:1}.quote-copy span{color:#a05c92;font-size:10px;font-weight:800;letter-spacing:.09em}.quote-copy p{max-width:860px;margin:8px 0 0;color:#57365f;font-size:clamp(17px,1.9vw,24px);font-weight:690;line-height:1.65}.quote-enter-active,.quote-leave-active{transition:opacity .35s ease,transform .35s ease}.quote-enter-from{opacity:0;transform:translateY(8px)}.quote-leave-to{opacity:0;transform:translateY(-5px)}@media(max-width:650px){.quote-stage{gap:13px;min-height:120px;padding:21px 18px;border-radius:21px}.quote-mark{width:45px;height:45px;border-radius:14px}.quote-copy p{font-size:16px}}@media(prefers-reduced-motion:reduce){.quote-enter-active,.quote-leave-active{transition:none}}
</style>
