export type AnniversaryKind='anniversary'|'birthday'|'travel'|'custom'
export type Anniversary={id:string;title:string;eventDate:string;kind:AnniversaryKind;recurring:boolean;note:string;createdBy:string}
const anniversaries=ref<Anniversary[]>([]);const relationshipStart=ref('2023-01-02');const anniversariesLoading=ref(false)
function localDate(value:string){const[y,m,d]=value.split('-').map(Number);return new Date(y!,m!-1,d!)}
function startOfToday(){const now=new Date();return new Date(now.getFullYear(),now.getMonth(),now.getDate())}
export function occurrence(event:Anniversary){const base=localDate(event.eventDate);if(!event.recurring)return base;const today=startOfToday();let next=new Date(today.getFullYear(),base.getMonth(),base.getDate());if(next<today)next=new Date(today.getFullYear()+1,base.getMonth(),base.getDate());return next}
export function daysUntil(event:Anniversary){return Math.max(0,Math.round((occurrence(event).getTime()-startOfToday().getTime())/86400000))}
export function useAnniversaries(){const{$supabase}=useNuxtApp();const{profile,demoMode}=useCoupleAuth()
const loveDays=computed(()=>Math.max(1,Math.floor((startOfToday().getTime()-localDate(relationshipStart.value).getTime())/86400000)+1));const sorted=computed(()=>[...anniversaries.value].sort((a,b)=>daysUntil(a)-daysUntil(b)));const nextAnniversary=computed(()=>sorted.value[0]||null)
function saveDemo(){localStorage.setItem('couple-space-anniversaries',JSON.stringify(anniversaries.value))}
async function loadAnniversaries(){if(!import.meta.client||anniversariesLoading.value)return;anniversariesLoading.value=true;try{if(!$supabase||demoMode.value){relationshipStart.value=localStorage.getItem('couple-space-start')||'2023-01-02';anniversaries.value=JSON.parse(localStorage.getItem('couple-space-anniversaries')||'null')||[{id:'ann-1',title:'第一次旅行纪念日',eventDate:'2023-07-26',kind:'travel',recurring:true,note:'第一次一起看海',createdBy:'demo-user'}];return}const[{data:couple,error:coupleError},{data,error}]=await Promise.all([$supabase.from('couples').select('relationship_start').eq('id',profile.value!.coupleId).single(),$supabase.from('anniversaries').select('*').order('event_date')]);if(coupleError)throw coupleError;if(error)throw error;relationshipStart.value=couple.relationship_start;anniversaries.value=(data||[]).map((r:any)=>({id:r.id,title:r.title,eventDate:r.event_date,kind:r.kind,recurring:r.recurring,note:r.note||'',createdBy:r.created_by}))}finally{anniversariesLoading.value=false}}
async function createAnniversary(input:Omit<Anniversary,'id'|'createdBy'>){if(!$supabase||demoMode.value){anniversaries.value.push({...input,id:crypto.randomUUID(),createdBy:profile.value?.id||'demo-user'});saveDemo();return}const{error}=await $supabase.from('anniversaries').insert({couple_id:profile.value!.coupleId,created_by:profile.value!.id,title:input.title,event_date:input.eventDate,kind:input.kind,recurring:input.recurring,note:input.note||null});if(error)throw error;await loadAnniversaries()}
async function updateAnniversary(id:string,input:Partial<Anniversary>){if(!$supabase||demoMode.value){const i=anniversaries.value.findIndex(x=>x.id===id);if(i>=0)anniversaries.value[i]={...anniversaries.value[i]!,...input};saveDemo();return}const payload:any={};if(input.title!==undefined)payload.title=input.title;if(input.eventDate!==undefined)payload.event_date=input.eventDate;if(input.kind!==undefined)payload.kind=input.kind;if(input.recurring!==undefined)payload.recurring=input.recurring;if(input.note!==undefined)payload.note=input.note||null;const{error}=await $supabase.from('anniversaries').update(payload).eq('id',id);if(error)throw error;await loadAnniversaries()}
async function deleteAnniversary(item:Anniversary){if(!$supabase||demoMode.value){anniversaries.value=anniversaries.value.filter(x=>x.id!==item.id);saveDemo();return}const{error}=await $supabase.from('anniversaries').delete().eq('id',item.id);if(error)throw error;anniversaries.value=anniversaries.value.filter(x=>x.id!==item.id)}
return{anniversaries,relationshipStart,loveDays,sorted,nextAnniversary,anniversariesLoading,loadAnniversaries,createAnniversary,updateAnniversary,deleteAnniversary}}
