export type MemberProfile={id:string;displayName:string;avatarUrl:string;email?:string}
const members=ref<MemberProfile[]>([]);const accountLoading=ref(false)
export function useAccountManagement(){const{$supabase}=useNuxtApp();const{profile,demoMode}=useCoupleAuth()
async function signedAvatar(path:string){if(!path)return'';const{data}=await $supabase!.storage.from('avatars').createSignedUrl(path,3600);return data?.signedUrl||''}
async function loadMembers(){if(!$supabase||demoMode.value){members.value=[{id:profile.value?.id||'demo-user',displayName:profile.value?.displayName||'我',avatarUrl:''},{id:'demo-partner',displayName:profile.value?.partnerName||'等待伴侣加入',avatarUrl:''}];return}accountLoading.value=true;try{const{data,error}=await $supabase.rpc('get_couple_profiles');if(error)throw error;members.value=await Promise.all((data||[]).map(async(r:any)=>({id:r.user_id,displayName:r.display_name,avatarUrl:await signedAvatar(r.avatar_url||'')})))}finally{accountLoading.value=false}}
async function updateName(name:string){if(!$supabase||demoMode.value){if(profile.value)profile.value.displayName=name;await loadMembers();return}const{error}=await $supabase.from('profiles').update({display_name:name}).eq('id',profile.value!.id);if(error)throw error;if(profile.value)profile.value.displayName=name;await loadMembers()}
async function uploadAvatar(file:File){if(!$supabase||demoMode.value)return URL.createObjectURL(file);const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${profile.value!.id}/avatar.${ext}`;const{error}=await $supabase.storage.from('avatars').upload(path,file,{contentType:file.type,upsert:true});if(error)throw error;const{error:updateError}=await $supabase.from('profiles').update({avatar_url:path}).eq('id',profile.value!.id);if(updateError)throw updateError;await loadMembers();return members.value.find(x=>x.id===profile.value!.id)?.avatarUrl||''}
async function regenerateInvitation(){if(!$supabase||demoMode.value)return'LOVE-7286';const{data,error}=await $supabase.rpc('regenerate_couple_invitation');if(error)throw error;return data as string}
async function unlinkCouple(){if(!$supabase||demoMode.value)return;const{error}=await $supabase.rpc('leave_couple_space');if(error)throw error}
async function updateRelationshipStart(value:string){if(!value)throw new Error('请选择在一起的日期');if(value>new Date().toISOString().slice(0,10))throw new Error('在一起的日期不能晚于今天');if(!$supabase||demoMode.value){localStorage.setItem('couple-space-start',value);return}const{error}=await $supabase.from('couples').update({relationship_start:value}).eq('id',profile.value!.coupleId);if(error)throw error}
return{members,accountLoading,loadMembers,updateName,updateRelationshipStart,uploadAvatar,regenerateInvitation,unlinkCouple}}
