type DailyAnswer={id:string;userId:string;answer:string;createdAt:string}
export type AiSavedWork={id:string;kind:'date_plan'|'diary'|'love_letter';workDate:string;title:string;content:string;memoryId:string;createdAt:string}
const dailyQuestion=ref<{id:string;question:string;date:string}|null>(null);const dailyAnswers=ref<DailyAnswer[]>([]);const aiLoading=ref(false)
export function useHeartAi(){const{$supabase}=useNuxtApp();const{profile}=useCoupleAuth()
async function generate(feature:string,payload:Record<string,unknown>={}){if(!$supabase)throw new Error('Supabase 尚未配置');aiLoading.value=true;try{const{data,error}=await $supabase.functions.invoke('heart-ai',{body:{feature,...payload}});if(error){let detail='';try{const response=(error as any).context as Response|undefined;if(response)detail=(await response.clone().json())?.error||''}catch{}throw new Error(detail||error.message||'AI 服务暂时不可用')}if(data?.error)throw new Error(data.error);return data.output as string}finally{aiLoading.value=false}}
async function loadDailyQuestion(){if(!$supabase||!profile.value?.coupleId)return;const today=new Date().toISOString().slice(0,10);let{data}=await $supabase.from('daily_questions').select('*').eq('couple_id',profile.value.coupleId).eq('question_date',today).maybeSingle();if(!data){const question=await generate('daily_question');const result=await $supabase.from('daily_questions').insert({couple_id:profile.value.coupleId,question_date:today,question}).select().single();if(result.error){const retry=await $supabase.from('daily_questions').select('*').eq('couple_id',profile.value.coupleId).eq('question_date',today).single();data=retry.data}else data=result.data}dailyQuestion.value={id:data.id,question:data.question,date:data.question_date};await loadAnswers()}
async function loadAnswers(){if(!$supabase||!dailyQuestion.value)return;const{data,error}=await $supabase.from('daily_answers').select('*').eq('question_id',dailyQuestion.value.id).order('created_at');if(error)throw error;dailyAnswers.value=(data||[]).map((r:any)=>({id:r.id,userId:r.user_id,answer:r.answer,createdAt:r.created_at}))}
async function submitAnswer(answer:string){if(!$supabase||!dailyQuestion.value)throw new Error('今日问题尚未生成');const{error}=await $supabase.from('daily_answers').upsert({question_id:dailyQuestion.value.id,user_id:profile.value!.id,answer},{onConflict:'question_id,user_id'});if(error)throw error;await loadAnswers()}
async function loadWorks(){if(!$supabase)return[];const{data,error}=await $supabase.from('ai_saved_works').select('*').order('work_date',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;return(data||[]).map((r:any)=>({id:r.id,kind:r.kind,workDate:r.work_date,title:r.title,content:r.content,memoryId:r.memory_id||'',createdAt:r.created_at}))as AiSavedWork[]}
async function saveWork(kind:'date_plan'|'diary'|'love_letter',content:string,date:string,title:string){if(!$supabase)throw new Error('Supabase 尚未配置');let memoryId='';if(kind==='diary'){const{data:existing}=await $supabase.from('ai_saved_works').select('id,memory_id').eq('couple_id',profile.value!.coupleId).eq('kind','diary').eq('work_date',date).maybeSingle();if(existing?.memory_id){const{error}=await $supabase.from('memories').update({content,memory_date:date,updated_at:new Date().toISOString()}).eq('id',existing.memory_id);if(error)throw error;memoryId=existing.memory_id;const{error:workError}=await $supabase.from('ai_saved_works').update({content,title,updated_at:new Date().toISOString()}).eq('id',existing.id);if(workError)throw workError;return}const{data:memory,error}=await $supabase.from('memories').insert({couple_id:profile.value!.coupleId,author_id:profile.value!.id,content,memory_date:date,photos:[]}).select('id').single();if(error)throw error;memoryId=memory.id}const{error}=await $supabase.from('ai_saved_works').insert({couple_id:profile.value!.coupleId,user_id:profile.value!.id,kind,work_date:date,title,content,memory_id:memoryId||null});if(error)throw error}
const myAnswer=computed(()=>dailyAnswers.value.find(x=>x.userId===profile.value?.id));const bothAnswered=computed(()=>dailyAnswers.value.length>=2)
return{dailyQuestion,dailyAnswers,myAnswer,bothAnswered,aiLoading,generate,loadDailyQuestion,submitAnswer,loadWorks,saveWork}}
