import { createMediaSignedUrl } from './useMediaUrls'
export type ChatMessage={id:string;senderId:string;content:string;mediaPath:string;mediaUrl:string;mediaType:'image'|'video'|'audio'|'';legacyMedia:boolean;readAt:string;createdAt:string}
export type LiveLocation={lat:number;lng:number;accuracy:number;updatedAt:string;sharing:boolean}
const messages=ref<ChatMessage[]>([]);const messagesLoading=ref(false);const messagesLoadingMore=ref(false);const messagesHasMore=ref(true);let oldestMessageCursor='';let messageChannel:any=null;let reconnectTimer:ReturnType<typeof setTimeout>|null=null;let reconnectAttempt=0;let intentionallyDisconnected=false;let networkListenersReady=false
export function useMessages(){const{$supabase}=useNuxtApp();const{profile,demoMode}=useCoupleAuth();const{recordActivity}=useCouplePet();const unreadCount=computed(()=>messages.value.filter(x=>x.senderId!==profile.value?.id&&!x.readAt).length)
const liveLocations=ref<Record<string,LiveLocation>>({})
function clearReconnect(){if(reconnectTimer){clearTimeout(reconnectTimer);reconnectTimer=null}}
function queueReconnect(delay?:number){if(intentionallyDisconnected||!$supabase||demoMode.value||!profile.value?.coupleId)return;clearReconnect();const wait=delay??Math.min(15000,Math.max(800,1000*2**reconnectAttempt));reconnectAttempt=Math.min(reconnectAttempt+1,5);reconnectTimer=setTimeout(()=>{reconnectTimer=null;void subscribe()},wait)}
function networkOnline(){reconnectAttempt=0;queueReconnect(0)}
function setupNetworkListeners(){if(!import.meta.client||networkListenersReady)return;window.addEventListener('online',networkOnline);networkListenersReady=true}
async function mediaUrl(path:string,legacy=false,mediaType:ChatMessage['mediaType']='image'){return createMediaSignedUrl($supabase,path,legacy?'memory-photos':'message-media',mediaType==='image'?{width:900,height:900,resize:'contain',quality:80}:undefined)}
  function normalizeContent(value: unknown): string {
    if (typeof value === 'string') return value
    if (value == null) return ''
    if (typeof value === 'object') {
      const record = value as Record<string, unknown>
      if (typeof record.text === 'string') return record.text
      if (typeof record.content === 'string') return record.content
    }
    return String(value)
  }
  function mapRow(r:any):ChatMessage{const path=r.media_path||r.image_path||'';return{id:String(r.id||crypto.randomUUID()),senderId:String(r.sender_id||''),content:normalizeContent(r.content),mediaPath:String(path||''),mediaUrl:'',mediaType:r.media_type||(path?'image':''),legacyMedia:!r.media_path&&!!r.image_path,readAt:String(r.read_at||''),createdAt:String(r.created_at||new Date().toISOString())}}
async function fetchMessagePage(before=''){if(!$supabase||demoMode.value)return[];let query=$supabase.from('messages').select('*').order('created_at',{ascending:false}).limit(30);if(before)query=query.lt('created_at',before);const{data,error}=await query;if(error)throw error;return Promise.all((data||[]).map(async r=>{const x=mapRow(r);x.mediaUrl=await mediaUrl(x.mediaPath,x.legacyMedia,x.mediaType);return x}))}
async function loadMessages(){if(!import.meta.client||messagesLoading.value)return;messagesLoading.value=true;try{if(!$supabase||demoMode.value){const raw=JSON.parse(localStorage.getItem('couple-space-messages')||'[]');const all=Array.isArray(raw)?raw.map(mapRow):[];messages.value=all.slice(-30);oldestMessageCursor=messages.value[0]?.createdAt||'';messagesHasMore.value=all.length>messages.value.length;return}const page=(await fetchMessagePage()).reverse();messages.value=page;oldestMessageCursor=page[0]?.createdAt||'';messagesHasMore.value=page.length===30}finally{messagesLoading.value=false}}
async function loadOlderMessages(){if(messagesLoadingMore.value||!messagesHasMore.value||!import.meta.client)return;messagesLoadingMore.value=true;try{if(!$supabase||demoMode.value){const all=JSON.parse(localStorage.getItem('couple-space-messages')||'[]').map(mapRow);const currentIndex=all.findIndex((item:ChatMessage)=>item.id===messages.value[0]?.id);const firstIndex=Math.max(0,currentIndex-30);const older=all.slice(firstIndex,Math.max(0,currentIndex));messages.value=[...older,...messages.value];messagesHasMore.value=firstIndex>0;oldestMessageCursor=messages.value[0]?.createdAt||'';return}if(!oldestMessageCursor){messagesHasMore.value=false;return}const older=(await fetchMessagePage(oldestMessageCursor)).reverse();messages.value=[...older,...messages.value];messagesHasMore.value=older.length===30;oldestMessageCursor=older[0]?.createdAt||oldestMessageCursor}finally{messagesLoadingMore.value=false}}
async function subscribe(){if(!$supabase||demoMode.value||messageChannel||!profile.value?.coupleId)return;intentionallyDisconnected=false;setupNetworkListeners();const channel=$supabase.channel(`messages:${profile.value.coupleId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`couple_id=eq.${profile.value.coupleId}`},async(payload:any)=>{if(messages.value.some(x=>x.id===payload.new.id))return;const x=mapRow(payload.new);x.mediaUrl=await mediaUrl(x.mediaPath,x.legacyMedia,x.mediaType);messages.value.push(x)}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'messages',filter:`couple_id=eq.${profile.value.coupleId}`},(payload:any)=>{const i=messages.value.findIndex(x=>x.id===payload.new.id);if(i>=0)messages.value[i]={...messages.value[i]!,readAt:payload.new.read_at||''}}).on('postgres_changes',{event:'DELETE',schema:'public',table:'messages',filter:`couple_id=eq.${profile.value.coupleId}`},(payload:any)=>{messages.value=messages.value.filter(x=>x.id!==payload.old.id)}).on('broadcast',{event:'live-location'},({payload}:any)=>{const senderId=String(payload?.senderId||'');if(!senderId||senderId===profile.value?.id)return;if(payload?.sharing===false){const next={...liveLocations.value};delete next[senderId];liveLocations.value=next;return}const lat=Number(payload?.lat),lng=Number(payload?.lng),accuracy=Number(payload?.accuracy);if([lat,lng,accuracy].every(Number.isFinite))liveLocations.value={...liveLocations.value,[senderId]:{lat,lng,accuracy,updatedAt:String(payload.updatedAt||new Date().toISOString()),sharing:true}}});messageChannel=channel;channel.subscribe(async(status:string)=>{if(messageChannel!==channel)return;if(status==='SUBSCRIBED'){reconnectAttempt=0;await loadMessages();return}if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(status)){messageChannel=null;await $supabase.removeChannel(channel).catch(()=>undefined);queueReconnect()}})}
async function broadcastLiveLocation(location:Omit<LiveLocation,'updatedAt'>|null){if(!messageChannel||!profile.value?.id)return;await messageChannel.send({type:'broadcast',event:'live-location',payload:{senderId:profile.value.id,sharing:!!location,...(location||{}),updatedAt:new Date().toISOString()}})}
async function send(content:string,file?:File){let path='';let url='';const mediaType:'image'|'video'|'audio'|''=file?(file.type.startsWith('audio/')?'audio':file.type.startsWith('video/')?'video':'image'):'';if(file){if(!$supabase||demoMode.value){url=await new Promise<string>((resolve,reject)=>{const r=new FileReader;r.onload=()=>resolve(r.result as string);r.onerror=reject;r.readAsDataURL(file)})}else{const ext=file.name.split('.').pop()?.toLowerCase()||(mediaType==='audio'?'webm':mediaType==='video'?'mp4':'jpg');path=`${profile.value!.coupleId}/messages/${crypto.randomUUID()}.${ext}`;const{error}=await $supabase.storage.from('message-media').upload(path,file,{contentType:file.type});if(error)throw error;url=await mediaUrl(path,false,mediaType)}}if(!$supabase||demoMode.value){messages.value.push({id:crypto.randomUUID(),senderId:profile.value?.id||'demo-user',content,mediaPath:path,mediaUrl:url,mediaType,legacyMedia:false,readAt:'',createdAt:new Date().toISOString()});localStorage.setItem('couple-space-messages',JSON.stringify(messages.value));void recordActivity();return}const{error}=await $supabase.from('messages').insert({couple_id:profile.value!.coupleId,sender_id:profile.value!.id,content:content||null,media_path:path||null,media_type:mediaType||null});if(error)throw error;void recordActivity()}
async function recall(message:ChatMessage){if(message.senderId!==profile.value?.id)throw new Error('只能撤回自己发送的消息');if(!$supabase||demoMode.value){messages.value=messages.value.filter(x=>x.id!==message.id);localStorage.setItem('couple-space-messages',JSON.stringify(messages.value));return}const{error}=await $supabase.from('messages').delete().eq('id',message.id).eq('sender_id',profile.value!.id);if(error)throw error;messages.value=messages.value.filter(x=>x.id!==message.id);if(message.mediaPath&&!message.legacyMedia)await $supabase.storage.from('message-media').remove([message.mediaPath])}
async function markRead(){const unread=messages.value.filter(x=>x.senderId!==profile.value?.id&&!x.readAt);if(!unread.length)return;const now=new Date().toISOString();if(!$supabase||demoMode.value){unread.forEach(x=>x.readAt=now);localStorage.setItem('couple-space-messages',JSON.stringify(messages.value));return}await $supabase.from('messages').update({read_at:now}).in('id',unread.map(x=>x.id))}
async function reconnect(){reconnectAttempt=0;clearReconnect();if(messageChannel&&$supabase)await $supabase.removeChannel(messageChannel).catch(()=>undefined);messageChannel=null;intentionallyDisconnected=false;await subscribe()}
async function disconnect(){intentionallyDisconnected=true;clearReconnect();if(messageChannel&&$supabase)await $supabase.removeChannel(messageChannel);messageChannel=null;liveLocations.value={};if(import.meta.client&&networkListenersReady){window.removeEventListener('online',networkOnline);networkListenersReady=false}}
return{messages,messagesLoading,messagesLoadingMore,messagesHasMore,unreadCount,liveLocations,loadMessages,loadOlderMessages,subscribe,reconnect,send,broadcastLiveLocation,recall,markRead,disconnect}}
