export type ListCategory = 'wish' | 'travel' | 'movie' | 'date'
export type ListPriority = 'low' | 'normal' | 'high'
export type TogetherItem = { id:string; title:string; note:string; category:ListCategory; priority:ListPriority; plannedDate:string; completed:boolean; completedBy:string; createdBy:string; createdAt:string }
const items=ref<TogetherItem[]>([]);const listLoading=ref(false)
const demoSeed:TogetherItem[]=[
  {id:'list-1',title:'一起看完爱乐之城',note:'准备零食和投影仪',category:'movie',priority:'normal',plannedDate:'2026-07-13',completed:true,completedBy:'demo-user',createdBy:'demo-user',createdAt:'2026-07-01'},
  {id:'list-2',title:'去大理住一周',note:'想看洱海的日出',category:'travel',priority:'high',plannedDate:'2026-10-02',completed:false,completedBy:'',createdBy:'demo-user',createdAt:'2026-07-02'},
  {id:'list-3',title:'做一本纸质照片书',note:'选出今年最喜欢的 30 张照片',category:'wish',priority:'normal',plannedDate:'',completed:false,completedBy:'',createdBy:'demo-user',createdAt:'2026-07-03'},
]
export function useTogetherList(){const{$supabase}=useNuxtApp();const{profile,demoMode}=useCoupleAuth();const{recordActivity}=useCouplePet()
function saveDemo(){localStorage.setItem('couple-space-list',JSON.stringify(items.value))}
async function loadItems(){if(!import.meta.client||listLoading.value)return;listLoading.value=true;try{if(!$supabase||demoMode.value){items.value=JSON.parse(localStorage.getItem('couple-space-list')||'null')||demoSeed;return}const{data,error}=await $supabase.from('together_items').select('*').order('completed').order('created_at',{ascending:false});if(error)throw error;items.value=(data||[]).map((r:any)=>({id:r.id,title:r.title,note:r.note||'',category:r.category,priority:r.priority,plannedDate:r.planned_date||'',completed:r.completed,completedBy:r.completed_by||'',createdBy:r.created_by,createdAt:r.created_at}))}finally{listLoading.value=false}}
async function createItem(input:Omit<TogetherItem,'id'|'completed'|'completedBy'|'createdBy'|'createdAt'>){if(!$supabase||demoMode.value){items.value.unshift({...input,id:crypto.randomUUID(),completed:false,completedBy:'',createdBy:profile.value?.id||'demo-user',createdAt:new Date().toISOString()});saveDemo();return}const{error}=await $supabase.from('together_items').insert({couple_id:profile.value!.coupleId,created_by:profile.value!.id,title:input.title,note:input.note||null,category:input.category,priority:input.priority,planned_date:input.plannedDate||null});if(error)throw error;await loadItems()}
async function updateItem(id:string,input:Partial<TogetherItem>){if(!$supabase||demoMode.value){const i=items.value.findIndex(x=>x.id===id);if(i>=0)items.value[i]={...items.value[i]!,...input};saveDemo();return}const payload:any={};if(input.title!==undefined)payload.title=input.title;if(input.note!==undefined)payload.note=input.note||null;if(input.category!==undefined)payload.category=input.category;if(input.priority!==undefined)payload.priority=input.priority;if(input.plannedDate!==undefined)payload.planned_date=input.plannedDate||null;const{error}=await $supabase.from('together_items').update(payload).eq('id',id);if(error)throw error;await loadItems()}
async function toggleItem(item:TogetherItem){const completed=!item.completed;if(!$supabase||demoMode.value){await updateItem(item.id,{completed,completedBy:completed?(profile.value?.id||'demo-user'):''});if(completed)void recordActivity();return}const{error}=await $supabase.from('together_items').update({completed,completed_by:completed?profile.value!.id:null,completed_at:completed?new Date().toISOString():null}).eq('id',item.id);if(error)throw error;await loadItems();if(completed)void recordActivity()}
async function deleteItem(item:TogetherItem){if(!$supabase||demoMode.value){items.value=items.value.filter(x=>x.id!==item.id);saveDemo();return}const{error}=await $supabase.from('together_items').delete().eq('id',item.id);if(error)throw error;items.value=items.value.filter(x=>x.id!==item.id)}
return{items,listLoading,loadItems,createItem,updateItem,toggleItem,deleteItem}}
